// core/commands/yardim.js — Command list
"use strict";
const { C } = require("../../tui/colors.ts");
const i18n = require("../i18n.js");

const HELP_EN = () => [
  "",
  C.bold("Basic"),
  `  ${C.cyan("/info")}                         Session summary: backend, tokens, cost`,
  `  ${C.cyan("/mode")} [chat|plan|build|agent]  Show or change working mode`,
  `  ${C.cyan("/reset")}                        Clear the conversation`,
  `  ${C.cyan("/undo")}                         Undo the last message pair`,
  "",
  C.bold("Model & Provider (BYOK)"),
  `  ${C.cyan("/model")}                        Active model + detected providers`,
  `  ${C.cyan("/model or")} [filter]            OpenRouter model list`,
  `  ${C.cyan("/model hf")}                     HuggingFace model list`,
  `  ${C.cyan("/model")} <backend> <id>         Switch model  (e.g. /model openrouter x/y)`,
  `  ${C.cyan("/model")} <id>                   Switch model only`,
  `  ${C.cyan("/provider")}                     All providers + status`,
  `  ${C.cyan("/provider presets")}             Ready-made services (groq, deepseek, xai...)`,
  `  ${C.cyan("/provider add")} <name> [url]    Add provider (preset or OpenAI-compat URL)`,
  `  ${C.cyan("/provider key")} <name> <key>    Save API key (never printed to screen)`,
  "",
  C.bold("MCP"),
  `  ${C.cyan("/mcp")}                          Defined servers + connection status`,
  `  ${C.cyan("/mcp connect")} <name>           Connect to server, expose its tools to the model`,
  `  ${C.cyan("/mcp tools")} <name>             List a server's tools`,
  `  ${C.cyan("/mcp add")} <name> <cmd|url>     Define a server (stdio or HTTP)`,
  `  ${C.cyan("/mcp disconnect")} <name>  ${C.cyan("/mcp remove")} <name>  Disconnect / remove definition`,
  "",
  C.bold("Session"),
  `  ${C.cyan("/gecmis")}                       Current conversation history (aliases: history)`,
  `  ${C.cyan("/sessions")}                     List saved sessions`,
  `  ${C.cyan("/load")} <id>                    Load a session`,
  `  ${C.cyan("/delete")} <id>                  Delete a session`,
  `  ${C.cyan("/dal")} [label]                  Fork the conversation into a branch`,
  `  ${C.cyan("/tree")}                         Show the session tree`,
  `  ${C.cyan("/checkpoint")}                   File snapshots (auto before writes)`,
  `  ${C.cyan("/checkpoint geri")} <id>         Restore a file from snapshot`,
  "",
  C.bold("Memory"),
  `  ${C.cyan("/memory")}                       List all memory by category`,
  `  ${C.cyan("/skill")}                        Procedural memory: list saved skills`,
  `  ${C.cyan("/skill mine")}                   Mine telemetry for repeating tool patterns → propose skill`,
  `  ${C.cyan("/skill read")} <name>            Show skill content`,
  `  ${C.cyan("/skill delete")} <name>          Delete skill`,
  `  ${C.cyan("/memory search")} <query>        Semantic memory search`,
  `  ${C.cyan("/memory add")} <text>            Add memory manually`,
  `  ${C.cyan("/memory delete")} <id>           Delete a memory entry`,
  "",
  C.bold("Vault"),
  `  ${C.cyan("/vault")}                        List the last 10 sessions`,
  `  ${C.cyan("/vault search")} <query>         Semantic vault search`,
  `  ${C.cyan("/vault read")} <id>              Show session contents`,
  `  ${C.cyan("/vault save")}                   Save the current conversation to vault`,
  `  ${C.cyan("/vault graph")}                  Rebuild the session-tag graph view`,
  `  ${C.cyan("/vault map")}                    Concept map: k-means clusters + PCA 2D scatter`,
  `  ${C.cyan("/vault digest")}                 Lovelace weekly digest (idle-time analysis)`,
  `  ${C.cyan("/vault status")}                 Daemon status and vault directory`,
  "",
  C.bold("Extend"),
  `  ${C.cyan("/plugin")}                       Installed plugins (~/.orion/plugins)`,
  `  ${C.cyan("/plugin reload")}                Reload all plugins`,
  "",
  C.bold("Settings"),
  `  ${C.cyan("/settings")}                     Full persistent config`,
  `  ${C.cyan("/settings tier1")} <model>       Ollama model`,
  `  ${C.cyan("/settings tier2")} <backend> <model>  Cloud backend/model`,
  `  ${C.cyan("/settings budget")} <usd>        Session budget limit`,
  `  ${C.cyan("/settings threshold")} <token>   Complexity threshold`,
  `  ${C.cyan("/settings vault")} <dir>         Vault directory`,
  `  ${C.cyan("/settings ollama")} <host>       Ollama server address`,
  `  ${C.cyan("/settings memoryEffort")} <low|balanced|high>  Extraction depth + thinking (high = extended thinking ON)`,
  "",
  C.bold("Router"),
  `  ${C.cyan("/router")}                       Routing settings`,
  `  ${C.cyan("/router")} aggressive|balanced|quality`,
  "",
  C.bold("Cost & Log"),
  `  ${C.cyan("/budget")}                       Token + cost summary`,
  `  ${C.cyan("/stats")} [days]                 Telemetry: cost/model, tool usage, routing, errors`,
  `  ${C.cyan("/log")}                          Recent session logs`,
  `  ${C.cyan("/log read")} <id>                Log detail`,
  "",
  C.bold("Tools"),
  `  ${C.cyan("/read")} <file>                  Show file contents`,
  `  ${C.cyan("/search")} <pattern>              Search text in files`,
  `  ${C.cyan("/glob")} <pattern>               Find files by glob (e.g. **/*.js)`,
  `  ${C.cyan("/git")} [status|diff|log|add|commit]  Git operations`,
  `  ${C.cyan("/test")} [pattern]               Run project tests`,
  `  ${C.cyan("/fix")} [test-command]           Run tests + auto-fix failures with AI`,
  `  ${C.cyan("/diff")} [file] [file2]          Diff vs last checkpoint, or two files`,
  `  ${C.cyan("/plan")} <task>                  Plan-only mode (read/search, no writes)`,
  `  ${C.cyan("/approve")} [extra]              Approve plan and implement`,
  `  ${C.cyan("/subagent")} <task>              Run a sub-agent`,
  `  ${C.cyan("/coordinator")} <task>           Multi-agent coordinator`,
  "",
  C.bold("Language"),
  `  ${C.cyan("/language")} [en|tr]             Show or change UI language`,
  "",
  C.bold("Modes"),
  `  ${C.dim("chat")}   Chat without tools       ${C.dim("plan")}   Read/search only`,
  `  ${C.dim("build")}  Files + commands         ${C.dim("agent")}  Full agent (default)`,
  "",
  C.dim("Ctrl+C  → interrupt output    Ctrl+C ×2  → exit"),
  C.dim('orion -p "question"  → one-shot mode (answer and exit)'),
  C.dim("node orion-server.js  → HTTP server (client/server mode)"),
  "",
].join("\n");

const HELP_TR = () => [
  "",
  C.bold("Temel"),
  `  ${C.cyan("/info")}                        Oturum özeti: backend, token, maliyet`,
  `  ${C.cyan("/mode")} [chat|plan|build|agent]  Çalışma modunu göster veya değiştir`,
  `  ${C.cyan("/reset")}                       Konuşmayı temizle`,
  `  ${C.cyan("/undo")}                        Son mesaj çiftini geri al`,
  "",
  C.bold("Model & Sağlayıcı (BYOK)"),
  `  ${C.cyan("/model")}                       Aktif model + algılanan sağlayıcılar`,
  `  ${C.cyan("/model or")} [filtre]           OpenRouter model listesi`,
  `  ${C.cyan("/model hf")}                    HuggingFace model listesi`,
  `  ${C.cyan("/model")} <backend> <id>        Model değiştir  (ör: /model openrouter x/y)`,
  `  ${C.cyan("/model")} <id>                  Sadece model değiştir`,
  `  ${C.cyan("/provider")}                    Tüm sağlayıcılar + durumları`,
  `  ${C.cyan("/provider presets")}            Hazır servisler (groq, deepseek, xai...)`,
  `  ${C.cyan("/provider add")} <ad> [url]     Sağlayıcı ekle (preset ya da OpenAI-compat URL)`,
  `  ${C.cyan("/provider key")} <ad> <key>     API anahtarı kaydet (asla ekrana yazılmaz)`,
  "",
  C.bold("MCP"),
  `  ${C.cyan("/mcp")}                         Tanımlı sunucular + bağlantı durumu`,
  `  ${C.cyan("/mcp connect")} <ad>            Sunucuya bağlan, araçlarını modele aç`,
  `  ${C.cyan("/mcp tools")} <ad>              Sunucunun araçlarını listele`,
  `  ${C.cyan("/mcp add")} <ad> <komut|url>    Sunucu tanımla (stdio ya da HTTP)`,
  `  ${C.cyan("/mcp disconnect")} <ad>  ${C.cyan("/mcp remove")} <ad>  Bağlantıyı kes / tanımı sil`,
  "",
  C.bold("Oturum"),
  `  ${C.cyan("/gecmis")}                      Mevcut konuşma geçmişi (aliases: history)`,
  `  ${C.cyan("/sessions")}                    Kayıtlı oturumları listele`,
  `  ${C.cyan("/load")} <id>                   Oturum yükle`,
  `  ${C.cyan("/delete")} <id>                 Oturum sil`,
  `  ${C.cyan("/dal")} [etiket]                Konuşmayı yeni dala ayır`,
  `  ${C.cyan("/tree")}                        Oturum ağacını göster`,
  `  ${C.cyan("/checkpoint")}                  Dosya snapshot'ları (yazım öncesi otomatik)`,
  `  ${C.cyan("/checkpoint geri")} <id>        Dosyayı snapshot'tan geri al`,
  "",
  C.bold("Hafıza"),
  `  ${C.cyan("/memory")}                      Tüm hafızayı kategoriye göre listele`,
  `  ${C.cyan("/skill")}                       Prosedürel bellek: kayıtlı skill'leri listele`,
  `  ${C.cyan("/skill maden")}                 Telemetry'den tekrar eden araç kalıpları → skill öner`,
  `  ${C.cyan("/skill oku")} <ad>              Skill içeriğini göster`,
  `  ${C.cyan("/skill sil")} <ad>              Skill sil`,
  `  ${C.cyan("/memory search")} <sorgu>       Semantik hafıza araması`,
  `  ${C.cyan("/memory add")} <metin>          Manuel hafıza ekle`,
  `  ${C.cyan("/memory delete")} <id>          Hafıza kaydını sil`,
  "",
  C.bold("Vault"),
  `  ${C.cyan("/vault")}                       Son 10 oturumu listele`,
  `  ${C.cyan("/vault search")} <sorgu>        Semantik vault araması`,
  `  ${C.cyan("/vault read")} <id>             Oturum içeriğini göster`,
  `  ${C.cyan("/vault save")}                  Mevcut konuşmayı vault'a kaydet`,
  `  ${C.cyan("/vault graf")}                  Oturum-etiket graf görünümünü üret`,
  `  ${C.cyan("/vault harita")}               Kavram haritası: k-means kümeleri + PCA 2D`,
  `  ${C.cyan("/vault digest")}               Lovelace haftalık özet (idle-time analizi)`,
  `  ${C.cyan("/vault status")}                Daemon durumu ve vault dizini`,
  "",
  C.bold("Genişletme"),
  `  ${C.cyan("/plugin")}                      Kurulu plugin'ler (~/.orion/plugins)`,
  `  ${C.cyan("/plugin yenile")}               Tüm plugin'leri yeniden yükle`,
  "",
  C.bold("Ayarlar"),
  `  ${C.cyan("/settings")}                    Tüm kalıcı config`,
  `  ${C.cyan("/settings tier1")} <model>      Ollama model`,
  `  ${C.cyan("/settings tier2")} <backend> <model>  Cloud backend/model`,
  `  ${C.cyan("/settings budget")} <usd>       Oturum bütçe limiti`,
  `  ${C.cyan("/settings threshold")} <token>  Karmaşıklık eşiği`,
  `  ${C.cyan("/settings vault")} <dizin>      Vault dizini`,
  `  ${C.cyan("/settings ollama")} <host>      Ollama sunucu adresi`,
  `  ${C.cyan("/ayar hafizayon")} <low|balanced|high>  Extraction derinliği + thinking (high = extended thinking AÇIK)`,
  "",
  C.bold("Router"),
  `  ${C.cyan("/router")}                       Routing ayarları`,
  `  ${C.cyan("/router")} aggressive|balanced|quality`,
  "",
  C.bold("Maliyet & Log"),
  `  ${C.cyan("/budget")}                      Token + maliyet özeti`,
  `  ${C.cyan("/stats")} [gün]                 Telemetri: maliyet/model, araç, routing, hatalar`,
  `  ${C.cyan("/log")}                         Son oturum logları`,
  `  ${C.cyan("/log read")} <id>               Log detayı`,
  "",
  C.bold("Araçlar"),
  `  ${C.cyan("/read")} <dosya>                Dosya içeriğini göster`,
  `  ${C.cyan("/search")} <pattern>             Dosyalarda metin ara`,
  `  ${C.cyan("/glob")} <pattern>              Glob ile dosya bul (örn. **/*.js)`,
  `  ${C.cyan("/git")} [status|diff|log|add|commit]  Git işlemleri`,
  `  ${C.cyan("/test")} [pattern]              Proje testlerini çalıştır`,
  `  ${C.cyan("/fix")} [test-komutu]           Testleri çalıştır + hataları AI ile otomatik düzelt`,
  `  ${C.cyan("/diff")} [dosya] [dosya2]       Son checkpoint'e ya da iki dosya arası fark`,
  `  ${C.cyan("/plan")} <görev>               Plan modu (sadece okuma/arama, yazma yok)`,
  `  ${C.cyan("/approve")} [ek-talimat]        Planı onayla ve uygula`,
  `  ${C.cyan("/subagent")} <görev>            Alt-ajan çalıştır`,
  `  ${C.cyan("/coordinator")} <görev>         Multi-agent koordinatör`,
  "",
  C.bold("Dil"),
  `  ${C.cyan("/language")} [en|tr]            Arayüz dilini göster veya değiştir`,
  "",
  C.bold("Modlar"),
  `  ${C.dim("chat")}   Araçsız sohbet          ${C.dim("plan")}   Sadece okuma/arama`,
  `  ${C.dim("build")}  Dosya + komut           ${C.dim("agent")}  Tam ajan (varsayılan)`,
  "",
  C.dim("Ctrl+C  → üretimi kes    Ctrl+C ×2  → çıkış"),
  C.dim('orion -p "soru"  → tek atış modu (cevapla ve çık)'),
  C.dim("node orion-server.js  → HTTP sunucu (client/server modu)"),
  "",
].join("\n");

module.exports = [{
  name:    "help",
  aliases: ["yardim", "?", "h"],
  group:   "General",
  desc:    "Command list",
  usage:   "/help",
  exec:    async () => console.log(i18n.getLocale() === "tr" ? HELP_TR() : HELP_EN()),
}];
